"""add branch location fields

Revision ID: 5fcf97fa7f7f
Revises: 0001_initial_schema
Create Date: 2026-06-03 19:41:14.600259
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5fcf97fa7f7f'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('google_maps_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'google_maps_url')
    op.drop_column('branches', 'address')
    # ### end Alembic commands ###
